### ISSUE TITLE
Apartment SMG Talent has wrong description.

### ISSUE THREAD

**Issue by oGkspAz** [mxswat/mx-division-builds#120]
Thanks for the updates and work so far!

I noticed yesterday that **The Apartment** SMG has the correct talent, **Perfectly Measured**, but it has the description of **Perfectly Ignited** instead.
![mxswat_apartment](https://github.com/mxswat/mx-division-builds/assets/13630539/7e5dac1c-a654-4c76-8f64-85e0e696cccf)

**Comment by Kiochyy** [comment]
I can see the issue, and it has now been fixed. If it still shows the wrong text, you can force download the update by going to "issue or bug?" in the top corner and pressing "clean local DB".

Thanks for the report, nice catch!
