### ISSUE TITLE
Normal Determined talent incorrect description

### ISSUE THREAD

**Issue by oGkspAz** [mxswat/mx-division-builds#121]
The normal version of Determined does not have the "killing an enemy will not retrigger the talent." in game. Only Perfectly Determined does (sadly).
![mxswat-Determined](https://github.com/mxswat/mx-division-builds/assets/13630539/848ce6c7-8ef1-4640-812c-0ca689bc3cd3)

**Comment by oGkspAz** [comment]
In case it was unclear, as a correction I meant:

**Determined**: After killing an enemy with
a headshot the next shot landed on any
enemy will be a guaranteed headshot

**Perfectly Determined**: After killing an enemy
with a headshot the next shot landed on any
enemy will be a guaranteed critical headshot.
While the talent is active, killing an enemy will
not retrigger the talent

**Comment by Kiochyy** [comment]
" From experience, the base talent definitely retriggers the talent. (White Death w. Determined + Chain Killer Hotshot builds)" OH!

Well in that case I'll confirm that it does retrigger, and change the description accordingly! Thanks a lot for the report!

**Comment by Kiochyy** [comment]
Just confirmed and updated our database. Thanks again for the report! this should be fixed.
