### ISSUE TITLE
Gear not appearing

### ISSUE THREAD

**Issue by s1mp7y-b3n** [mxswat/mx-division-builds#124]
When opening the menu to pick a gear piece (mask, backpack, etc.) nothing appears, there is only the Blank Slot option. Neither cleaning the local DB nor refreshing the page fix this issue.
<img width="776" alt="TD2 bug ss" src="https://github.com/mxswat/mx-division-builds/assets/167969180/574e512f-481b-4c92-b165-9b2681a7157f">

**Comment by Rippertoo** [comment]
+1 on this

Search field finds nothing

a little annoying as I use this tool frequently :)

**Comment by Kiochyy** [comment]
Hi, I'm currently trying to pinpoint what caused it.

No ETA at the moment, I'm out of clues and franticly searching for what could have caused it. Can't promise it will be fixed today, but doing what I can to solve it asap.

Thanks for the report

**Comment by Kiochyy** [comment]
The issue should now be fixed. Thanks again for the report.

**Comment by s1mp7y-b3n** [comment]
Great one, thanks a lot! Your back must hurt from carrying this site lol.

**Comment by Kiochyy** [comment]
Thankfully, I'm not alone ;) All the new functionalities have been made by Shinmen, while I mostly handle the database and the player support.

Seing so many player report the issue heer and on discord was kinda heatwarming: it reminds me that people rely on the tool for their builds, and how much it helps them. Help *us* really, I'm a player aswell.
