### ISSUE TITLE
Would be great if there were some visual indicator of stability/range for weapons that mimics the in-game display

### ISSUE THREAD

**Issue by Eglin** [mxswat/mx-division-builds#22]
It would be great if there were some visual indicator of stability/range for weapons that mimics the in-game display.  I don't know how anyone else tends to build, but I usually have some target breakpoints in mind for stability and range and I have trouble identifying them with this tool.  Some displays that mimic the ones in-game would be useful, factoring mods and gear attributes in.

**Comment by mxswat** [comment]
Ah, I don't think it's possible, I don't have values for weapon spread unless a skilled hacker can get them from the game.
Or somebody data mines it
