### ISSUE TITLE
Ammo Dump holster missing an attribute

### ISSUE THREAD

**Issue by stephenfurmanek** [mxswat/mx-division-builds#27]
The +20% ammo capacity is taking up an attribute slot when it should not be, it is in addition to the two attribute slots

**Comment by mxswat** [comment]
Hi, I'm aware of this bug.

I can't fix it right now because it will require an entire rework of the database

A rework is already in progress but it will take weeks to be stable, so at the moment that bug is not a priority

**Comment by Kiochyy** [comment]
Hi

A workaround was added a while back, Ammo Dump has access to both it's minor since.

Thanks for the report
