### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by sixlive** [mxswat/mx-division-builds#3]
## Description
Currently on mobile all the columns are squashed together. The UI should adjust since its already a grid.

**Comment by sixlive** [comment]
I tried to take a stab at it but I don’t really know grid and I got all turned around.

**Comment by mxswat** [comment]
Hi thanks for the feedback I updated the read and the Responsive UI is in the roadmap
I'll leave this open and we can close it when I finish that task

**Comment by mxswat** [comment]
Task done a few days ago
