### ISSUE TITLE
Memento cores aren't functioning properly

### ISSUE THREAD

**Issue by Decorpus** [mxswat/mx-division-builds#32]
When having the Memento selected, it only activates the red core. In the drop down menu it doesn't give the option of picking even a different main core, so it's only showing up as 1 red.

**Comment by mxswat** [comment]
Hi, I'm aware of this bug.

I can't fix it right now because it will require an entire rework of the database

A rework is already in progress but it will take weeks to be stable, so at the moment that bug is not a priority

**Comment by Mementoskull** [comment]
Its already been a year, how far are you with the fix?

**Comment by Kiochyy** [comment]
Hi,

An update has just been pushed fixing memento on the V1(current version)

Closing this as solved

Thanks for the report
