### ISSUE TITLE
Negotiator's Dilemma with Critchance Issue with more than 2 Set Items and other Brand Crit Bonus

### ISSUE THREAD

**Issue by McRipolo** [mxswat/mx-division-builds#35]
Thanks for the tool, i have found an issue with Crit Brand Bonus.
I hope you understand the problem with this sampels, and can fix it.

3 Items ND -> Crit Chance 15%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECBJaZF5sVN1d1l9LirLZQA

3 Items ND and 1 Ceska Vyroba s.r.o. -> Crit Chance  15%-> should be 25%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECIAnCVaQdTArY2g3Yy0x+6-REA

Same Problem with 3 Items ND and 2 Providence Defense-> Crit Chance 15%-> should be 25%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECAzASWkvlZafXYoy80-Qqy50A

2 Items ND and 1 Ceska Vyroba s.r.o. -> Crit Chance  25%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjYgzADhzmMRAE4jKIETa0aqiG6XnHi2X6Ig

2 Items ND and 2 Providence Defense and 1 Ceska Vyroba s.r.o. -> Crit Chance  35% 
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjYgnDuQxAZiLLSW3OoWoMTpsYNvqaA

3 Items ND and 2 Providence Defense and 1 Ceska Vyroba s.r.o. > Crit Chance 15%-> should be 35%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjYgnDuQxAZiLLSW3OqXGoIXpqYZbMaA

**Comment by McRipolo** [comment]
Same problem with Crit Damage:

3 Items ND and 3 Providence Defense and 1 Ceska Vyroba s.r.o. -> Crit Damge 15% -> should be 35%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECAzASWkvlZacMfXQs24u263Sa0A

**Comment by mxswat** [comment]
@McRipolo Can I close this issue?

**Comment by McRipolo** [comment]
The Bug is still there:

3 Items ND and 1 Ceska Vyroba s.r.o. -> Crit Chance 15%-> should be 25%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECIAnCVaQdTArY2g3Yy0x+6-REA

Same Problem with 3 Items ND and 2 Providence Defense-> Crit Chance 15%-> should be 25%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjY424YBsOECAzASWkvlZafXYoy80-Qqy50A

3 Items ND and 2 Providence Defense and 1 Ceska Vyroba s.r.o. > Crit Chance 15%-> should be 35%
https://mxswat.github.io/mx-division-builds/#/EwRgtADJ1bOQLmAFnnA7AVjYgnDuQxAZiLLSW3OqXGoIXpqYZbMaA

**Comment by Kiochyy** [comment]
Hi,

I can't replicate it on my end, and the link appear with the correct crit chance values. I assume this has been fixed since.

Closing this as solved, please reopen if you encounter this issue again.
