### ISSUE TITLE
Is it possible to add Skills to the tool?

### ISSUE THREAD

**Issue by TheBlameCarrier** [mxswat/mx-division-builds#70]
To be honest this addition would this tool make (kind of) perfect.
I am using it to show certain builds in our clan, but there are always questions about the skills.
Are there any plans to add this?

**Comment by Kiochyy** [comment]
Hi,

Sorry for the late answer, I answer questions as they come on our discord but just recently discovered Github issues.

The Version2 will include skills , and is currently being worked on with no ETA yet.

As for the V1(current version), we are considering it but haven't made a move on it yet. We already have most of the data we need, so it is now a question to find a way and the time to add it.

So: It's planned for V2, and we want to do it for V1 but can't promise it yet.


Keeping this open as reference

**Comment by Kiochyy** [comment]
Update: A first version of skills has been in the builder for a little over 2 months now.
