### ISSUE TITLE
Mod Slot: optic - Rugged Mini Reflex Sight missing for Carbine 7

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#71]
I am unable to add the "Rugged Mini Reflex Sight" optics mod (+5% Critical Hit Chance) to the The Carbine 7 assault rifle, which the game allows.

**Comment by Kiochyy** [comment]
Hi,

I can replicate it on my end, I see the issue and will look into it. No ETA, the change might be more complicated than I expect it to.

Thanks for the report, it's on my todo list.

**Comment by Kiochyy** [comment]
Hi,

This has been fixed, the change was simple. 

Closing this as solved
