### ISSUE TITLE
Protection from Elites is not recalculated on changing Specialization

### ISSUE THREAD

**Issue by NoRefill** [mxswat/mx-division-builds#77]
Great tool! Thanks!

https://mxswat.github.io/mx-division-builds/#/MwTgtOCsYAxgbLMBGFcAsIBM1laXIQFzqKEoIrLArTl5j5zIDsM7zRk+04+ieZmw5hMONCiYFYRYCwhg601MgzYl5YsBrhUmiqrAAOaZtkm+pg3DJWYRHOiSr88rImAmjNZtCx6SJ2YYVDcPRBZ5X0kZdxU0XEiUFl0WE2QjOBAAOlwNEiA

Hopefully, the above link shows the build I had entered with 3 12% Protection from Elites mods and the Technician Specialization. The tool shows 36% PfE which is correct. I then realized that an extra 10% PfE could be gained by switching to the Survivalist Specialization, which I did, but the PfE total did not update. It should have gone up to 46% with this change.

**Comment by Kiochyy** [comment]
I can reporoduce it on my end, switching to survivalist doesn't add the 10% PfE to the stats. Added to our to do list.

Thanks for the report

**Comment by NoRefill** [comment]
Not sure if this is the same issue or not, but using Specialization Demolitionist for 10% Explosive Damage with 2 piece Grupo Sombra for 15% Explosive Damage only gives a total of 15% instead of 25% under Utility Cores, as in this example:

https://mxswat.github.io/mx-division-builds/#/MwNgtAjATG4Ay0nCklumBXMC4AsArGAJyQwLgRwDsqV65mTc+tpGFSAHHQvR81zA2ZQX3TZJuCCIHYU-KZJwRw7RvIljmOKMB4xitCAQUFgkAjBN50RDBDwqetqAlpQUoMNWN8intJQtLbmYPa0ICgg7P46wEA

**Comment by Kiochyy** [comment]
Yes, this is the same issue. I need to make a pass and check all the bonuses.

In the meantime tho, the survivalist 10% PfE bonus is now working

**Comment by Fooweb** [comment]
[AwWl7SOreAuArI2BGSqDMMICY5Tw4HGlEkWmEAsAbCNXpc+OVeyWy3Fx9L91bAgA](https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuArI2BGSqDMMICY5Tw4HGlEkWmEAsAbCNXpc+OVeyWy3Fx9L91bAgA)
