### ISSUE TITLE
Skill Tier (utility cores) are not being calculated correctly with NinjaBike + Picaro's Holster

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#78]
Reference build:  https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuArI2BGSqDMMICY5Tw4HGlEkWmEAsAbCNXpc+OVeyWy3Fx9L91bAgA

The build above should have two utility cores:

1. NinjaBike bag
2. Brazos 2-piece set bonus (due to being paired with NinjaBike)

**Comment by Fooweb** [comment]
This has now been corrected.
