### ISSUE TITLE
Named TDI "Kard" Custom pistol fixed attribute is not preserved in URL

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#79]
Reference build:  https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuGS4uo1Hlq53CcGbqElTF5zmnjwBMALAMwgCMArBdkA

When you open the above URL, it gets re-written to this URL and the fixed attribute on the pistol is lost...

https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuGS4uo1Hlq53CcGbqElTF5zmnjwBMALAMwVKJA

**Comment by Fooweb** [comment]
@wkrick - Fixed! Thanks for reporting!
