### ISSUE TITLE
URL is not saving core attributes for "Ammo Dump" and "Claws Out" holsters

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#81]
Steps to reproduce:

1. open a new blank build
2. add the "Ammo Dump" or "Claws Out" named holster
3. take note of the core attribute
4. copy the URL
5. open a new browser window
6. paste the URL into the address bar
7. go to URL
8. the core attribute will be blank

This doesn't appear to happen with "Forge", "Picaro's Holster", or any other named items in other slots that I tested so I think it's related to these items having an additional fixed attribute.

**Comment by Fooweb** [comment]
@wkrick Fixed! Thanks for reporting!
