### ISSUE TITLE
Gear and Gear mods Critical Chance not counted in the weapon stats

### ISSUE THREAD

**Issue by Kiochyy** [mxswat/mx-division-builds#82]
Gear and Gear mods Critical Chance not counted in the weapon stats, but weapon mods and watch is.

Discord links of the reports, for reference and additional data:

https://discord.com/channels/702180050791039016/705147074676785262/1080570501866475650
"
The live build currently doesn't appear to be applying Crit Chance to the weapon properly.  This build has 40% crit chance from the watch and gear attributes but at the bottom the Capacitor is only showing a 20% crit chance total.    I don't thinkhttps://mxswat.github.io/mx-division-builds/#/MwRgtATGAMNgbHWympdAXAVi68iRh1Upjltcpgx8xgAONJsjEcU5zsmDAFkV6wO3EWgzAowrtPIRgATgRh5jEDhpYA7BoJZGLUYYyGuGCEA "

https://discord.com/channels/702180050791039016/705147074676785262/1080926024851787826
"hm... seems like chc isnt working.. tested with max watch, 1 ceska and 15 chc on weapon, yet chc shows 25% (should be 35% (10 +10+15) 

tested with zero chc on 1 ceska piece (no other stats or gear items) and max watch +15 chc weapon mods. so looks likes just counting watch + weapon mods."

**Comment by Fooweb** [comment]
Fixed! Adding correctly now! Thanks for reporting!
