### ISSUE TITLE
Claws Out holster - only one fixed attribute is shown in totals and they swap when loaded from URL

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#83]
Steps to reproduce:

1. create new blank build
2. add "Claws Out" holster
3. note the position of the attributes and note that melee damage is calculated in sidebar but not pistol damage
4. copy URL, open a new browser window, paste the URL into the address bar, go to URL
5. URL will change, attributes will swap places, pistol damage is in sidebar, but not melee damage

This is my original URL:  
https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuGS4uo1Hlq53CDMALJAIwAcelCONm6tS9VUTDLwQA

Note the position of the pistol and and melee damage.  Melee damage is shown in totals, but not pistol damage...  
![image](https://user-images.githubusercontent.com/10203734/222805415-32710310-418d-4812-8985-2a1d14d3f6b0.png)

After loading the above URL in a new window, it changes to this URL:  
https://mxswat.github.io/mx-division-builds/#/AwWl7SOreAuGS4uo1Hlq53CDMALJPgOx4UI7Wbo1J2VSP3PBA

Note the position of pistol and melee damage have swapped.  Pistol damage is shown in totals, but not melee damage...  
![image](https://user-images.githubusercontent.com/10203734/222807071-7965dd4f-56c1-453a-b353-881ae182d355.png)

**Comment by Fooweb** [comment]
@wkrick - Fixed! Adding correctly now! Thanks for reporting!
