### ISSUE TITLE
Missing 3-piece bonuses when using NinjaBike backpack with 2 pieces of some gearsets: Heartbreaker, Hotshot, Hunter's Fury

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#85]
Heartbreaker:
2 piece bonus: 15% AR Damage / 15% LMG Damage
3 piece bonus: 15% Weapon Handling

The 3-piece Weapon Handling bonus is missing:  
https://mxswat.github.io/mx-division-builds/#/CwNgtADJ1bP3RAuArC+BGaGDMj4BMCMS+Zx5sSwwFdlJDT9p9blrzZn7CPXjIA

Hotshot:
2 piece bonus: 30% Marksman Rifle Damage / 30% Stability
3 piece bonus: 30% Headshot Damage

The 3-piece Headshot Damage bonus is missing:  
https://mxswat.github.io/mx-division-builds/#/CwTgtADJ1bP3RAuArC+BGaGDMj4BMCMS+Zx5sSwAHBfZSY8w6Q+5Wy2Vxwr9yZA

Hunter's Fury:
2 piece bonus: 15% SMG Damage / 15% Shotgun Damage
2 piece bonus: 20% Armor on Kill / 100% Health on Kill

The 3-piece Armor on Kill and Health on Kill bonuses are missing:  
https://mxswat.github.io/mx-division-builds/#/CwBgtOkdWz8gFwFZnwIzXQZjlATAjInkaeYjmdecbfTSTcxQ6y2U2wiUA

**Comment by Fooweb** [comment]
Fixed!
