### ISSUE TITLE
SHD Watch levels are not reflected in URL

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#88]
The SHD Watch levels are not encoded in the URL.  I don't know if this is by design or if it's a bug.  I could see it going either way.

Steps to reproduce:

1. Open a build URL.  e.g.: https://mxswat.github.io/mx-division-builds/#/EwWgDOkdWz8C55xctTWbXD29fFwP3RONSLMSoptMtuKA
2. Click the "Set 0 SHD" button
3. Notice that the URL doesn't change
4. Click the "Set Max SHD" button
5. Notice that the URL doesn't change

**Comment by Fooweb** [comment]
@wkrick 

The idea is that SHD Watch levels are a per user setting and are saved locally for the user to change or use for their watch level and not specific to the build and this is by design.

**Comment by wkrick** [comment]
Makes sense.  Works as designed.  This can be closed.
