### ISSUE TITLE
Mod Slot: optic - Rugged Mini Reflex Sight missing for TKB-408 and Kingbreaker

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#91]
The builder doesn't allow you to equip this optical mod on the TKB-401 and its named variant, "Kingbreaker"...

Rugged Mini Reflex Sight
+5.0% Critical Hit Chance

Here's a screenshot from in-game showing the mod is available on this weapon...

![image](https://user-images.githubusercontent.com/10203734/232857801-1d1d285f-28dd-4244-8a09-d490c0f2058d.png)

**Comment by wkrick** [comment]
@Kiochyy - This is the same issue as https://github.com/mxswat/mx-division-builds/issues/71

I'm not really sure how the mod data is organized.  Is this a problem that can be fixed globally, or do we need to go through and check all 250+ weapons individually and verify which mods are compatible and which aren't?

**Comment by Fooweb** [comment]
Info updated for both TKB-401 and Kingbreaker. Don't think we need to go through all weapons individually and can just update each weapon as required.
